apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    db: restaurant-postgres
data:
  init.sql: |
    CREATE DATABASE restaurantdb_tasty;
    CREATE DATABASE restaurantdb_order;

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-postgres
  labels:
    db: restaurant-postgres
spec:
  selector:
    matchLabels:
      db: restaurant-postgres
  template:
    metadata:
      labels:
        db: restaurant-postgres
    spec:
      containers:
        - name: restaurant-postgres
          image: postgres:14.4
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password 
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-config-volume
      volumes:
        - name: postgres-config-volume
          configMap:
            name: postgres-config

---

apiVersion: v1
kind: Service
metadata:
  name: restaurant-postgres
  labels:
    db: restaurant-postgres
spec:
  type: ClusterIP
  selector:
    db: restaurant-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432