apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/dreevo/restaurant-edge-service/k8s?ref=main
configMapGenerator:
- behavior: merge
  files:
  - application-staging.yml
  name: edge-config
images:
- name: edge-service
  newName: ghcr.io/dreevo/edge-service
  newTag: latest
replicas:
- count: 1
  name: edge-service
patches:
- path: patch-env.yml
