version: "3.8" 
services: 
 tasty-service: 
  depends_on:
    - restaurant-postgres 
  image: "tasty-service" 
  container_name: "tasty-service" 
  ports: 
    - 9001:9001
    - 8001:8001
  environment: 
    - BPL_JVM_THREAD_COUNT=50 
    - SPRING_DATASOURCE_URL=jdbc:postgresql://restaurant-postgres:5432/restaurantdb_catalog
    - SPRING_PROFILES_ACTIVE=testdata 
    - BPL_DEBUG_ENABLED=true
    - BPL_DEBUG_PORT=8001
 restaurant-postgres: 
  image: "postgres:14.4"
  container_name: "restaurant-postgres"
  ports:
    - 5432:5432
  environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=restaurantdb_catalog