version: "3.8"
services:
  tasty-service:
    depends_on:
      - restaurant-postgres
    image: "tasty-service"
    container_name: "tasty-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://restaurant-postgres:5432/restaurantdb_tasty
      - SPRING_PROFILES_ACTIVE=testdata

  order-service:
    depends_on:
      - restaurant-postgres
    image: "order-service"
    container_name: "order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - RESTAURANT_TASTY_SERVICE_URI=http://tasty-service:9001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://restaurant-postgres:5432/restaurantdb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://restaurant-postgres:5432/restaurantdb_order
      - SPRING_RABBITMQ_HOST=restaurant-rabbitmq
  
  config-service:
    image: "config-service"
    container_name: "config-service"
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888

  edge-service:
    depends_on:
      - restaurant-redis
    image: "edge-service"
    container_name: "edge-service"
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - SPA_URL=http://restaurant-ui:9004
      - TASTY_SERVICE_URL=http://tasty-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_REDIS_HOST=restaurant-redis
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://host.docker.internal:8080/realms/restaurant

  dispatcher-service:
    depends_on:
      - restaurant-rabbitmq
    image: "dispatcher-service"
    container_name: dispatcher-service
    ports:
      - 9003:9003
      - 8003:8003
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8003
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_RABBITMQ_HOST=restaurant-rabbitmq
      

      
  restaurant-postgres:
    image: "postgres:14.10"
    container_name: "restaurant-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes: 
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  restaurant-redis:
    image: "redis:7.0" 
    container_name: "restaurant-redis"
    ports:
      - 6379:6379 

  restaurant-rabbitmq:
    image: rabbitmq:3.10-management
    container_name: restaurant-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes: 
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  restaurant-ui:
    image: "restaurant-ui" 
    container_name: "restaurant-ui"
    ports:
      - 9004:9004 
    environment:
      - PORT=9004 

  restaurant-keycloak: 
    image: quay.io/keycloak/keycloak:19.0
    container_name: "restaurant-keycloak"
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment: 
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - 8080:8080