apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/dreevo/restaurant-menu-service/k8s?ref=main
configMapGenerator:
- behavior: merge
  files:
  - application-staging.yml
  name: tasty-config
images:
- name: tasty-service
  newName: ghcr.io/dreevo/tasty-service
  newTag: latest
replicas:
- count: 2
  name: tasty-service
patches:
- path: patch-env.yml
